#oracle 
driver=oracle.jdbc.OracleDriver
url=jdbc:oracle:thin:@localhost:1521:xe
username=scott
password=kosa1004

#mysql 
#driver=com.mysql.cj.jdbc.Driver
#url=jdbc:mariadb://localhost:13306/kosa_db?useUnicode=true&characterEncoding=UTF-8
#username=scott
#password=kosa1004


#mariadb  
#driver=org.mariadb.jdbc.Driver
#url=jdbc:mariadb://localhost:23306/kosa_db?useUnicode=true&characterEncoding=UTF-8
#username=root
#password=kosa1004
